trigger:
  - main

pr: none

resources:
  repositories:
  - repository: templates
    type: github
    endpoint: John D Watson
    name: johnwatson484/azure-devops-templates
    ref: refs/tags/1

extends:
  template: build.yaml@templates
  parameters:
    name: pace-calculator
    project: PaceCalculator
    framework: net
    deploy: true
    namespace: pace-calculator

