apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ quote .Values.name }}
  labels: 
    {{- include "pace-calculator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  strategy: {}
  selector:
    matchLabels:
      {{- include "pace-calculator.selector-labels" . | nindent 6 }}
  template:
    metadata:
      labels: 
        {{- include "pace-calculator.labels" . | nindent 8 }}
      annotations:
        redeployOnChange: {{ quote .Values.deployment.redeployOnChange }}
    spec:
      volumes:
      - name: temp-dir
        emptyDir: {}
      securityContext:
        runAsUser: {{ .Values.deployment.runAsUser }}
        runAsNonRoot: {{ .Values.deployment.runAsNonRoot }}
      restartPolicy: {{ quote .Values.deployment.restartPolicy }}
      containers:
      - name: {{ quote .Values.name }}
        image: {{ quote .Values.image }}
        imagePullPolicy: {{ quote .Values.container.imagePullPolicy }}
        securityContext:
          readOnlyRootFilesystem: {{ .Values.container.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.container.allowPrivilegeEscalation }}
        ports:
        - containerPort: {{ .Values.container.port }}
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp
          name: temp-dir
        resources:
          requests:
            memory: {{ quote .Values.container.requestMemory }}
            cpu: {{ quote .Values.container.requestCpu }}
          limits:
            memory: {{ quote .Values.container.limitMemory }}
            cpu: {{ quote .Values.container.limitCpu }}

