apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ quote .Values.name }}
  labels: {{ include "pace-calculator.labels" . | trimSuffix "\n" | indent 2 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  strategy: {}
  selector:
    matchLabels:
      {{- include "pace-calculator.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "pace-calculator.labels" . | trimSuffix "\n" | indent 6 }}
      annotations:
        redeployOnChange: {{ quote .Values.deployment.redeployOnChange }}
    spec:
      volumes:
      - name: temp-client
        emptyDir: {}
      - name: temp-proxy
        emptyDir: {}
      - name: temp-fastcgi
        emptyDir: {}
      - name: temp-uwsgi
        emptyDir: {}
      - name: temp-scgi
        emptyDir: {}
      - name: temp-run
        emptyDir: {}
      securityContext:
        runAsUser: {{ .Values.deployment.runAsUser }}
        runAsNonRoot: {{ .Values.deployment.runAsNonRoot }}
      restartPolicy: {{ quote .Values.deployment.restartPolicy }}
      containers:
      - name: {{ quote .Values.name }}
        image: {{ quote .Values.image }}
        imagePullPolicy: {{ quote .Values.container.imagePullPolicy }}
        securityContext:
          readOnlyRootFilesystem: {{ .Values.container.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .Values.container.allowPrivilegeEscalation }}
        env:
        - name: NODE_ENV
          value: {{ quote .Values.environment }}
        - name: PORT
          value: {{ quote .Values.container.port }}
        ports:
        - containerPort: {{ .Values.container.port }}
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /var/cache/nginx/client_temp
          name: temp-client
        - mountPath: /var/cache/nginx/proxy_temp
          name: temp-proxy
        - mountPath: /var/cache/nginx/fastcgi_temp
          name: temp-fastcgi
        - mountPath: /var/cache/nginx/uwsgi_temp
          name: temp-uwsgi
        - mountPath: /var/cache/nginx/scgi_temp
          name: temp-scgi
        - mountPath: /var/run
          name: temp-run
        resources:
          requests:
            memory: {{ quote .Values.container.requestMemory }}
            cpu: {{ quote .Values.container.requestCpu }}
          limits:
            memory: {{ quote .Values.container.limitMemory }}
            cpu: {{ quote .Values.container.limitCpu }}

