apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ quote .Values.name }}
  labels: 
    {{- include "pace-calculator.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
  selector: 
    {{- include "pace-calculator.selector-labels" . | nindent 4 }}
  type: {{ quote .Values.service.type }}
